name: Wokwi CI (Local Project)

on:
  push:
  pull_request:

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PlatformIO
        uses: platformio/action@v1

      - name: Build firmware
        run: pio run

      - name: Install Wokwi CLI
        run: |
          curl -s https://wokwi.com/ci/install.sh | sh

      - name: Run Wokwi Simulation
        run: |
          wokwi-cli \
            --project . \
            --firmware .pio/build/esp32dev/firmware.elf \
            --scenario test-sim.json \
            --timeout 20000
