name: Wokwi CI (Local Project)

on:
  push:
  pull_request:

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build firmware
        run: pio run

      - name: Install Wokwi CLI (latest)
        run: |
          wget -q https://github.com/wokwi/wokwi-cli/releases/latest/download/wokwi-cli-linux-static
          mv wokwi-cli-linux-static /usr/local/bin/wokwi
          chmod +x /usr/local/bin/wokwi

      - name: Wokwi version
        run: wokwi --version

      - name: Debug wokwi.toml bytes
        run: |
          xxd -g 1 -l 80 wokwi.toml || true

      - name: Debug wokwi.toml
        run: |
          sed -n '1p' wokwi.toml | sed 's/./& /g'
          cat -A wokwi.toml

      - name: Run Wokwi Simulation
        run: |
          wokwi-cli . --elf .pio/build/esp32dev/firmware.elf --timeout 20000
        env:
          WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}
